apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-play-scala-seed-with-labels
  labels: 
        creation_method: manual
        env: prod
spec:
  containers:
  - image: play-scala-seed:1.0.8
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
